COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
#  SQLALCHEMY_DATABASE_URI: 'sqlite://'
#  SQLALCHEMY_DATABASE_URI: 'sqlite:///device_db.sqlite'
  SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://{0}:{1}@localhost/iot_db'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://{0}:{1}@localhost/iot_db'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: a1d2i3d4a5s6
